---

intellij_version    : "{{ intellij_year }}.{{ intellij_subversion }}"

desktop   : "jetbrains-idea-ce"

intellij:
  url     : "https://download-cf.jetbrains.com/idea/"
  zip     : "ideaIC-{{ intellij_version }}.tar.gz"
  home    : "/usr/lib/intellij"

  libraries:
    apt_prereq:
      - unzip
    choco:
      - intellijidea-community

  tags:
    - "dev"
    - "dev-ide"
    - "dev-ide-intellij"
    - "dev-ide-idea"
    - "intellij"
    - "idea"

