---

#################################################################

- name: "apt | install | no gui"
  apt:
    name  : "{{ libraries_apt }}"
    state : "latest"
  tags:
    - "general"

- name: "apt | install | gui"
  when:
    - gui | bool
  apt:
    name  : "{{ libraries_apt_gui }}"
    state : "latest"
  tags:
    - "general"

- name: "pip | install | no gui"
  pip:
    name  : "{{ libraries_pip }}"
    state : "latest"
  tags:
    - "general"

- name: "snap | install | no gui"
  snap:
    name  : "{{ libraries_snap }}"
    state : "present"
  tags:
    - "general"

#################################################################

- name: "additional mounts"
  when:
    - mount_points is iterable
  with_items:
    - "{{ mount_points }}"
  mount:
    path  : "{{ item.path }}"
    src   : "UUID={{ item.uuid }}"
    fstype: "{{ item.fs }}"
    opts  : "{{ item.opts | default( defaults.mount_opts ) }}"
    state : "mounted"
  tags:
    - "general"
    - "mount"

#################################################################

