---

#################################################################

- name: "install > apt"
  apt:
    name  : "{{ libraries_apt }}"
    state : "latest"
  tags:
    - "general"

- name: "install > pip"
  pip:
    name  : "{{ libraries_pip }}"
    state : "latest"
  tags:
    - "general"

- name: "install > snap"
  snap:
    name  : "{{ libraries_snap }}"
    state : "present"
  tags:
    - "general"

- name: "install > apt > gui only"
  when:
    - gui | bool
  apt:
    name  : "{{ libraries_apt_gui }}"
    state : "latest"
  tags:
    - "general"

- name: "install > pip > gui only"
  when:
    - gui | bool
  apt:
    name  : "{{ libraries_pip_gui }}"
    state : "latest"
  tags:
    - "general"

- name: "install > snap > gui only"
  when:
    - gui | bool
  snap:
    name  : "{{ libraries_snap_gui }}"
    state : "present"
  tags:
    - "general"

#################################################################

- name: "additional mounts"
  when:
    - mount_points is iterable
  with_items:
    - "{{ mount_points }}"
  mount:
    path  : "{{ item.path }}"
    src   : "UUID={{ item.uuid }}"
    fstype: "{{ item.fs }}"
    opts  : "{{ item.opts | default( defaults.mount_opts ) }}"
    state : "mounted"
  tags:
    - "general"
    - "mount"

#################################################################

