---

#################################################################

- name: "choco > config"
  win_chocolatey_config:
    name  : "proxy"
    state : "present"
    value : "http://euuktelsprx01.corp.internalroot.com:3128"
  tags:
    - "general"

- name: "choco > install"
  when:
    - libraries_choco | length > 0
  win_chocolatey:
    name    : "{{ libraries_choco }}"
    state   : "present"
  tags:
    - "general"

- name: "choco > install > gui"
  when:
    - is_gui
    - libraries_choco | length > 0
  win_chocolatey:
    name    : "{{ libraries_choco_gui }}"
    state   : "present"
  tags:
    - "general"

#################################################################

