---

libraries_apt:
  ubuntu:
    - "aptitude"
    - "libc6-i386"
    - "lib32z1"
#    - "lib32ncurses5"
    - "lib32stdc++6"
  ubuntu_gnome:
    - "gnome-panel"
  all:
#    - "python-pip"
    - "python3-pip"

