---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ intellij.home }}/{{ intellij_version }}"
    - "{{ primary_user.home }}/.IdeaIC{{ intellij_year }}"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "{{ intellij.tags }}"

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ intellij.libraries.apt_prereq }}"
    state   : "latest"
  tags:
    - "{{ intellij.tags }}"

#################################################################

- name: "unpack > application"
  become : "{{ primary_user.id }}"
  unarchive:
    src         : "{{ intellij.url }}{{ intellij.zip }}"
    dest        : "{{ intellij.home }}/{{ intellij_version }}"
    remote_src  : "yes"
    extra_opts  : [--strip-components=1]
    creates     : "{{ intellij.home }}/{{ intellij_version }}/bin/"
  tags:
    - "{{ intellij.tags }}"

- name: "unpack > application config"
  unarchive:
    src         : "files/config.tar.gz"
    dest        : "{{ primary_user.home }}/.IdeaIC{{ intellij_year }}"
    owner       : "{{ primary_user.id }}"
    group       : "{{ primary_user.id }}"
  tags:
    - "{{ intellij.tags }}"

#################################################################

- name: "launcher > desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "{{ intellij.tags }}"
    - "launcher"

- name    : "launcher > add"
  become  : "{{ primary_user.id }}"
  script  : "../../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: False
  tags:
    - "{{ intellij.tags }}"
    - "launcher"

#################################################################

