---

- hosts         : localhost
  become        : yes
  become_method : sudo
  gather_facts  : yes
  connection    : local

  vars:
    - proxy     : False
      has_gui   : False

      pi_user     : "{{ primary_user }}"
      all_users:
        - "{{ root_user     }}"
        - "{{ primary_user  }}"

  roles:
    - { role: checks                                                                                            }
    - { role: users                                                                                             }
    - { role: prereq                                                                                            }






    - { role: git                                                                                               }
    - { role: ssh                                                                                               }
    - { role: bash,                     bash_welcome        : "retropie"                                        }
    - { role: vim                                                                                               }
    - { role: powerline                                                                                         }
    - { role: general                                                                                           }

    - { role: keychain                                                                                          }

    - { role: retropie                                                                                          }

